project:
  type: website

website:
  page-navigation: true
  title: "Digital Agriculture"
  description: "Homepage for Digital Agriculture"
  site-url: "https://bovi-analytics.github.io/DigitalAgriculture/"

  repo-url: https://github.com/Bovi-analytics/DigitalAgriculture/
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@MielHostens"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Miel Hostens"
    background: "#d8f0f0"

  sidebar:
    background: "#d8f0f0"
    logo: "images/Bovi-Analytics-SmallLogo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Bovi-analytics/
        text: "GitHub organization"
      - icon: google
        href: https://colab.research.google.com/
        text: "Google colab"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: index.qmd
            text: Schedule
          - href: course-objectives.qmd
            text: Learning objectives
          - href: course-team.qmd
            text: Teaching team
          - href: course-support.qmd
            text: Support
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
      - section: "Supplemental notes"
        contents:
          - href: supplemental/operations-in-r.qmd
            text: Operations in R


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual